[project]
name = "dse-app"
version = "0.1.0"
description = "App for dse website specific page"
authors = [
    {name = "mdrayhan03", email = "phylosopherhossain2022@gmail.com"}
]
license = "MIT"
requires-python = ">=3.12"
dependencies = [
    "flet (>=1.0.1,<2.0.0)",
    "flet-webview (>=1.0.1,<2.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

# Added Flet build configuration section
[tool.flet]
org = "com.mdrayhan03"
product = "DSEApp"

[tool.flet.app]
path = "src/main.py"